language: go
go:
  - '1.11.x'
  - '1.12.x'
  - 'tip'
sudo: true
before_install:
  - ./travis-mecab-install.sh
  - export CGO_LDFLAGS="`mecab-config --libs`"
  - export CGO_CFLAGS="-I`mecab-config --inc-dir`"
