language: go
go:
- '1.2.x'
- '1.3.x'
- '1.4.x'
- '1.5.x'
- '1.6.x'
- '1.7.x'
- '1.8.x'
- '1.9.x'
- '1.10.x'
- '1.11.x'
- 'tip'
sudo: true
before_install:
- ./travis-mecab-install.sh
- export CGO_LDFLAGS="`mecab-config --libs`"
- export CGO_CFLAGS="-I`mecab-config --inc-dir`"
