name: test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  linux:
    strategy:
      matrix:
        go:
          - "1"
          - "1.15"
          - "1.14"
          - "1.13"
          - "1.12"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install mecab
        run: |
          .github/install-mecab-linux.sh
          echo "CGO_LDFLAGS=$(mecab-config --libs)" >> "$GITHUB_ENV"
          echo "CGO_CFLAGS=-I$(mecab-config --inc-dir)" >> "$GITHUB_ENV"
      - name: setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: test
        run: |
          go version
          go test -v -race ./...

  macos:
    strategy:
      matrix:
        go:
          - "1"
          - "1.15"
          - "1.14"
          - "1.13"
          - "1.12"
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install mecab
        run: |
          .github/install-mecab-darwin.sh
          echo "CGO_LDFLAGS=$(mecab-config --libs)" >> "$GITHUB_ENV"
          echo "CGO_CFLAGS=-I$(mecab-config --inc-dir)" >> "$GITHUB_ENV"
      - name: setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: test
        run: |
          go version
          go test -v -race ./...
