name: test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  linux:
    strategy:
      matrix:
        go:
          - '1.12'
          - '1.13'
          - '1'
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: install mecab
        run: |
          .github/install-mecab-linux.sh
          echo "::set-env name=CGO_LDFLAGS::$(mecab-config --libs)"
          echo "::set-env name=CGO_CFLAGS::-I$(mecab-config --inc-dir)"
      - uses: actions/checkout@v2
      - name: test
        run: |
          go test -v -race ./...
